### ISSUE TITLE
webpack usage?

### ISSUE THREAD

**Issue by lorvent** [davshoward/tux#2]
Hello,
i really like your project but i have a doubt...what does webpack do in this project?

i liked it for having gulp, nunjucks etc but i see that it uses webpack to bundle js files etc.

i have a doubt....is it possible to remove webpack and use it with just gulp?

thanks.

**Comment by davshoward** [comment]
Hey,

Thanks ;-)

A variety of reasons:
- It both bundles the JS files
- Sorts out the transpiling for browser support (based off of the .browserslistrc file)
- Hot reloading so the page will auto-reload when developing

I'm sure you "could" remove webpack but you'd lose the above features.

Cheers

**Comment by lorvent** [comment]
thanks for the response :)

my existing project folder structure is a bit different so i will try and update you :)

**Comment by lorvent** [comment]
Hello,
i guess we have similar plugins available for gulp as well.

can you pls tell me if there is any advantage of using webpack over gulp plugins?
thanks
